# Generated by Django 5.1.1 on 2024-10-09 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0003_alter_student_class_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examitem',
            name='class_name',
        ),
        migrations.RemoveField(
            model_name='homeworkitem',
            name='class_name',
        ),
        migrations.RemoveField(
            model_name='examgrade',
            name='exam_item',
        ),
        migrations.RemoveField(
            model_name='examgrade',
            name='student',
        ),
        migrations.RemoveField(
            model_name='examitem',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='homeworkgrade',
            name='homework_item',
        ),
        migrations.RemoveField(
            model_name='homeworkgrade',
            name='student',
        ),
        migrations.RemoveField(
            model_name='homeworkitem',
            name='subject',
        ),
        migrations.DeleteModel(
            name='Manager',
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
        migrations.DeleteModel(
            name='Class',
        ),
        migrations.DeleteModel(
            name='ExamGrade',
        ),
        migrations.DeleteModel(
            name='ExamItem',
        ),
        migrations.DeleteModel(
            name='HomeworkGrade',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='HomeworkItem',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
