# Generated by Django 5.1.1 on 2024-10-09 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0005_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examitem',
            name='class_name',
        ),
        migrations.RemoveField(
            model_name='examitem',
            name='course',
        ),
        migrations.RemoveField(
            model_name='homeworkgrade',
            name='homework_item',
        ),
        migrations.RemoveField(
            model_name='homeworkgrade',
            name='student',
        ),
        migrations.RemoveField(
            model_name='homeworkitem',
            name='class_name',
        ),
        migrations.RemoveField(
            model_name='homeworkitem',
            name='course',
        ),
        migrations.DeleteModel(
            name='ExamGrade',
        ),
        migrations.DeleteModel(
            name='ExamItem',
        ),
        migrations.DeleteModel(
            name='HomeworkGrade',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='HomeworkItem',
        ),
    ]
