# Generated by Django 5.1.1 on 2024-10-12 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0007_student_examitem_homeworkitem_homeworkgrade_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homeworkitem',
            name='course',
        ),
        migrations.RemoveField(
            model_name='examitem',
            name='course',
        ),
        migrations.RemoveField(
            model_name='examgrade',
            name='exam_item',
        ),
        migrations.RemoveField(
            model_name='examgrade',
            name='student',
        ),
        migrations.RemoveField(
            model_name='examitem',
            name='class_name',
        ),
        migrations.RemoveField(
            model_name='homeworkgrade',
            name='homework_item',
        ),
        migrations.RemoveField(
            model_name='homeworkgrade',
            name='student',
        ),
        migrations.RemoveField(
            model_name='homeworkitem',
            name='class_name',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='ExamGrade',
        ),
        migrations.DeleteModel(
            name='ExamItem',
        ),
        migrations.DeleteModel(
            name='HomeworkGrade',
        ),
        migrations.DeleteModel(
            name='HomeworkItem',
        ),
    ]
