# Generated by Django 5.1.1 on 2024-10-12 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0009_course_examitem_examgrade_homeworkitem_homeworkgrade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='course',
            name='description',
        ),
        migrations.AddField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(blank=True, to='grades.student'),
        ),
    ]
