# Generated by Django 5.1.1 on 2024-10-12 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0012_course_examitem_examgrade_homeworkitem_homeworkgrade'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grades.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grades.student')),
            ],
        ),
    ]
