# Generated by Django 5.1.1 on 2024-10-12 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0014_remove_examitem_class_name_remove_examitem_course_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='grade',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
