# Generated by Django 5.1.1 on 2024-10-13 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0015_alter_grade_grade'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Class',
        ),
    ]
