# Generated by Django 5.1.2 on 2024-10-16 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0017_alter_gradeitem_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gradeitem',
            name='category',
            field=models.CharField(choices=[('homework', 'Homework'), ('exam', 'Exam'), ('quiz', 'Quiz'), ('general performance', 'General performance')], max_length=30),
        ),
    ]
