# Generated by Django 5.1.2 on 2024-10-21 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0019_alter_gradeitem_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='google_oauth_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='student',
            name='line_user_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
