# Generated by Django 5.1.2 on 2024-10-23 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0020_student_google_oauth_id_student_line_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTPVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_user_id', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('otp', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
