# Generated by Django 5.1.2 on 2024-10-24 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0021_otpverification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='google_oauth_id',
        ),
    ]
