# Generated by Django 5.1.2 on 2024-10-24 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0022_remove_student_google_oauth_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='line_user_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
