# Generated by Django 5.1.2 on 2024-10-24 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0024_alter_student_line_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='line_user_id',
        ),
    ]
