# Generated by Django 5.1.2 on 2024-10-24 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0025_remove_student_line_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='line_user_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
