# Generated by Django 5.1.2 on 2024-10-24 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0026_student_line_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='last_category',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
