# Generated by Django 5.1.2 on 2024-10-24 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0027_grade_last_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade',
            name='last_category',
        ),
        migrations.AddField(
            model_name='student',
            name='last_category',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
