# Generated by Django 5.1.2 on 2024-10-24 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0028_remove_grade_last_category_student_last_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gradeitem',
            name='category',
            field=models.CharField(choices=[('homework', '作業'), ('exam', '段考'), ('quiz', '小考'), ('general performance', '平時成績'), ('Overall score', '總成績')], max_length=30),
        ),
    ]
