# Generated by Django 5.1.2 on 2024-10-24 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0029_alter_gradeitem_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='grade',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='gradeitem',
            name='category',
            field=models.CharField(choices=[('homework', '作業'), ('exam', '段考'), ('quiz', '小考'), ('general performance', '平時成績'), ('overall score', '總成績')], max_length=30),
        ),
    ]
